"""Gentle clues for Quiet Crossword, grouped by theme. Add freely: word -> clue."""

THEMES = {
    'Nature walk': {
        'tree': 'It grows leaves and gives shade',
        'leaf': 'A green part of a tree that turns gold in autumn',
        'oak': 'A tree that grows from an acorn',
        'acorn': 'A squirrel\'s favorite snack',
        'fern': 'A feathery green plant of shady woods',
        'moss': 'Soft green carpet on a shady stone',
        'river': 'Water flowing toward the sea',
        'brook': 'A small, babbling stream',
        'creek': 'A little stream, especially in America',
        'stone': 'A small rock you might skip on a lake',
        'pebble': 'A smooth little stone on the beach',
        'hill': 'A gentle rise in the land',
        'valley': 'Low land between hills',
        'meadow': 'A field of grass and wildflowers',
        'forest': 'A big place full of trees',
        'trail': 'A path through the woods',
        'path': 'A way to walk along',
        'bark': 'The rough outside of a tree',
        'twig': 'A tiny branch',
        'root': 'The part of a plant under the ground',
        'soil': 'Earth that plants grow in',
        'breeze': 'A soft, cool wind',
        'cloud': 'A fluffy shape in the sky',
        'rain': 'Drops falling from gray skies',
        'mist': 'A thin, soft fog',
        'dew': 'Tiny drops on grass in the morning',
        'lake': 'A large pool of still water',
        'shore': 'Where the land meets the water',
        'cliff': 'A steep rock face',
        'pine': 'A tree with needles and cones',
        'maple': 'A tree whose sap makes a sweet syrup',
        'birch': 'A tree with white, papery bark',
        'willow': 'A tree whose branches weep toward water',
        'grass': 'Green blades on a lawn',
        'sky': 'Blue above on a clear day',
    },
    'In bloom': {
        'rose': 'A classic flower with thorns and a sweet smell',
        'lily': 'A flower that can float on a pond',
        'daisy': 'A white flower with a yellow middle',
        'tulip': 'A cup-shaped spring flower',
        'petal': 'One of the soft parts of a flower',
        'bloom': 'To open into a flower',
        'bud': 'A flower before it opens',
        'seed': 'Plant it and it grows',
        'stem': 'The stalk that holds up a flower',
        'garden': 'A place to grow flowers and vegetables',
        'lilac': 'A purple shrub with a lovely scent',
        'poppy': 'A bright red flower of the fields',
        'violet': 'A small purple flower, or its color',
        'orchid': 'An elegant flower often given as a gift',
        'lotus': 'A water flower that rises from the mud',
        'clover': 'A small plant; find one with four leaves for luck',
        'ivy': 'A climbing plant on old walls',
        'herb': 'Basil or mint, for example',
        'mint': 'A fresh herb, lovely in tea',
        'basil': 'A herb that goes well with tomatoes',
        'sprout': 'A tiny new shoot',
        'grow': 'What plants do with sun and water',
        'water': 'What every plant needs to drink',
        'sun': 'It rises in the morning',
        'vase': 'A jar for cut flowers',
        'peony': 'A big, ruffled early-summer flower',
        'dahlia': 'A flower with many neat petals',
        'hedge': 'A row of bushes along a garden',
        'rake': 'A garden tool for gathering leaves',
        'shed': 'A little garden hut for tools',
    },
    'Night sky': {
        'moon': 'It shines at night and changes shape',
        'star': 'A twinkling light in the night sky',
        'night': 'The time for sleeping',
        'dusk': 'The soft light just after sunset',
        'dawn': 'The first light of morning',
        'dream': 'A story your mind tells while you sleep',
        'sleep': 'Rest with your eyes closed',
        'glow': 'A soft, steady light',
        'owl': 'A night bird that says "hoo"',
        'lunar': 'To do with the moon',
        'orbit': 'The path of a planet around the sun',
        'comet': 'An icy visitor with a glowing tail',
        'planet': 'Earth is one',
        'galaxy': 'A huge family of stars',
        'wish': 'Make one on a shooting star',
        'dark': 'Without light',
        'quiet': 'Hushed and peaceful',
        'still': 'Not moving at all',
        'calm': 'Peaceful and untroubled',
        'rest': 'A pause to recover',
        'lamp': 'A light by the bed',
        'candle': 'A wax light with a flame',
        'pillow': 'A soft place for your head',
        'nap': 'A short daytime sleep',
        'yawn': 'A sign you are sleepy',
        'cosmos': 'The whole universe',
        'shine': 'To give off light',
        'twinkle': 'What little stars do, in the song',
    },
    'Kindness': {
        'kind': 'Friendly, caring and warm',
        'care': 'To look after someone',
        'hug': 'A warm squeeze with both arms',
        'smile': 'A happy look on your face',
        'thank': 'Say this when someone helps you',
        'help': 'Lend a hand',
        'gift': 'A present',
        'share': 'Give some to someone else',
        'gentle': 'Soft and careful',
        'warm': 'Not cold; cozy',
        'love': 'A deep, caring feeling',
        'heart': 'A symbol of love',
        'friend': 'Someone you like and trust',
        'trust': 'To believe in someone',
        'hope': 'A feeling that good things can come',
        'joy': 'Great happiness',
        'peace': 'A calm with no fighting',
        'grace': 'Kindness and ease, even when it\'s hard',
        'mercy': 'Kindness shown when it isn\'t earned',
        'listen': 'Really hear what someone says',
        'praise': 'Words that say "well done"',
        'cheer': 'Happiness and encouragement',
        'honest': 'Telling the truth',
        'loyal': 'Always on someone\'s side',
        'patient': 'Able to wait calmly',
        'tender': 'Soft and loving',
        'thanks': 'A word of gratitude',
        'visit': 'Go to see someone',
        'lend': 'Give for a little while',
        'give': 'Hand over freely',
    },
    'Home and cozy': {
        'home': 'Where the heart is, they say',
        'house': 'A building where a family lives',
        'room': 'A space with four walls',
        'door': 'You open it to come in',
        'window': 'Glass you can look through',
        'roof': 'The top of a house',
        'porch': 'A covered place by the front door',
        'garden': 'Flowers and vegetables grow here',
        'kettle': 'It whistles when the water boils',
        'teapot': 'A pot for brewing tea',
        'mug': 'A big cup for cocoa',
        'cocoa': 'A warm chocolate drink',
        'blanket': 'A cozy cover for cold nights',
        'quilt': 'A blanket made from patchwork',
        'sofa': 'A long, soft seat for the living room',
        'couch': 'Another word for a sofa',
        'rug': 'A small carpet',
        'lamp': 'Turn it on to read',
        'chair': 'A seat with a back',
        'table': 'Where you eat dinner',
        'shelf': 'A place to keep books',
        'book': 'Pages to read',
        'oven': 'Where bread is baked',
        'bread': 'A loaf from the bakery',
        'soup': 'A warm meal in a bowl',
        'stew': 'A slow-cooked warm dish',
        'hearth': 'The floor of a fireplace',
        'slipper': 'A soft shoe for indoors',
        'towel': 'Use it to dry off after a bath',
        'bath': 'A warm soak in the tub',
        'cozy': 'Warm and snug',
        'nest': 'A bird\'s home',
    },
    'Animal friends': {
        'cat': 'A pet that purrs',
        'dog': 'A pet that wags its tail',
        'puppy': 'A young dog',
        'kitten': 'A young cat',
        'bunny': 'A soft hopping friend with long ears',
        'rabbit': 'An animal that loves carrots',
        'duck': 'A bird that says "quack"',
        'frog': 'A green hopper by the pond',
        'owl': 'A wise bird of the night',
        'fox': 'A clever orange animal with a bushy tail',
        'deer': 'A gentle animal of the forest',
        'fawn': 'A baby deer',
        'lamb': 'A baby sheep',
        'sheep': 'A woolly farm animal',
        'goat': 'A farm animal with a little beard',
        'horse': 'An animal you can ride',
        'pony': 'A small horse',
        'bear': 'A big furry animal that loves honey',
        'panda': 'A black and white bear that eats bamboo',
        'otter': 'A playful swimmer that holds hands while it sleeps',
        'robin': 'A bird with a red breast',
        'wren': 'A tiny brown songbird',
        'swan': 'A graceful white water bird',
        'bee': 'It makes honey',
        'snail': 'It carries its home on its back',
        'turtle': 'A slow animal with a shell',
        'mouse': 'A tiny animal that squeaks',
        'whale': 'The biggest animal in the sea',
        'koala': 'A sleepy tree-hugger from Australia',
        'llama': 'A woolly animal from the Andes',
        'paw': 'A dog\'s foot',
        'purr': 'The happy sound of a cat',
        'wag': 'What a happy dog\'s tail does',
        'hen': 'A mother chicken',
        'chick': 'A fluffy baby hen',
        'goose': 'A big bird that honks',
        'seal': 'A sea animal that claps its flippers',
        'mole': 'It digs tunnels underground',
    },
    'Tasty treats': {
        'cake': 'A sweet treat for a birthday',
        'pie': 'Apple ___',
        'tea': 'A warm drink, often with milk',
        'honey': 'Sweet and golden, made by bees',
        'jam': 'Fruit spread for toast',
        'toast': 'Bread browned until crisp',
        'butter': 'Spread it on warm bread',
        'apple': 'A crunchy red or green fruit',
        'pear': 'A fruit shaped like a light bulb',
        'peach': 'A fuzzy summer fruit',
        'plum': 'A small purple fruit',
        'berry': 'A small, juicy fruit',
        'cherry': 'A little red fruit on a stem',
        'lemon': 'A sour yellow fruit',
        'melon': 'A big juicy summer fruit',
        'grape': 'It grows in bunches on a vine',
        'mango': 'A sweet tropical fruit',
        'banana': 'A yellow fruit you peel',
        'cookie': 'A sweet, round treat from the jar',
        'muffin': 'A little cake for breakfast',
        'waffle': 'A breakfast treat with little squares',
        'candy': 'Lollipops and gumdrops',
        'sugar': 'It makes things sweet',
        'cream': 'Whipped, it goes on top',
        'milk': 'A white drink from cows',
        'egg': 'A hen lays one',
        'rice': 'Tiny grains, often served with curry',
        'pasta': 'Spaghetti, for example',
        'pizza': 'A round dish with cheese on top',
        'salad': 'A bowl of fresh greens',
        'soup': 'Eat it with a spoon',
        'picnic': 'A meal on a blanket outdoors',
        'snack': 'A little something between meals',
        'lunch': 'The midday meal',
        'dinner': 'The evening meal',
        'bake': 'Cook in the oven',
        'scone': 'A little cake for tea with jam and cream',
        'fudge': 'A soft, sweet treat',
        'cocoa': 'Hot chocolate',
    },
    'By the sea': {
        'sea': 'A big body of salty water',
        'ocean': 'The Pacific, for one',
        'wave': 'Water rolling onto the beach',
        'tide': 'The sea going in and out',
        'sand': 'Tiny grains on the beach',
        'shell': 'Find one on the shore and hold it to your ear',
        'beach': 'A sandy place by the sea',
        'boat': 'It floats on water',
        'sail': 'Catch the wind with it',
        'ship': 'A big boat',
        'crab': 'It walks sideways',
        'pearl': 'A gem found in an oyster',
        'coral': 'A colorful reef',
        'whale': 'A giant of the ocean',
        'seal': 'It barks on the rocks',
        'gull': 'A seaside bird',
        'pier': 'A walkway out over the water',
        'dune': 'A hill of sand',
        'shore': 'The edge of the sea',
        'salt': 'Seawater tastes of it',
        'swim': 'Move through water',
        'float': 'Rest on top of the water',
        'harbor': 'A safe place for boats',
        'island': 'Land with water all around',
        'anchor': 'It keeps a boat in place',
        'breeze': 'A light sea wind',
        'surf': 'Ride a wave on a board',
        'kite': 'Fly it on a windy beach',
        'yacht': 'A fancy sailing boat',
    },
    'Feelings': {
        'happy': 'Feeling good',
        'glad': 'Pleased',
        'calm': 'Relaxed and peaceful',
        'proud': 'Pleased with what you did',
        'brave': 'Ready to face something hard',
        'safe': 'Out of harm\'s way',
        'hope': 'Looking forward to good things',
        'joy': 'Deep happiness',
        'bliss': 'Perfect happiness',
        'relax': 'Let go and rest',
        'ease': 'Comfort, with no strain',
        'eager': 'Keen and excited',
        'amazed': 'Very surprised, in a good way',
        'cheer': 'Gladness',
        'content': 'Happy with what you have',
        'grateful': 'Thankful',
        'serene': 'Deeply calm',
        'steady': 'Calm and even',
        'rested': 'Refreshed after sleep',
        'loved': 'Cared for deeply',
        'mellow': 'Relaxed and easy-going',
        'upbeat': 'Cheerful and positive',
        'lively': 'Full of energy',
        'jolly': 'Merry and bright',
        'merry': 'Full of cheer',
        'sunny': 'Bright and cheerful',
        'curious': 'Wanting to know more',
        'gentle': 'Soft and kind',
    },
    'Seasons': {
        'spring': 'The season of new flowers',
        'summer': 'The warmest season',
        'autumn': 'The season of falling leaves',
        'winter': 'The coldest season',
        'snow': 'White flakes in winter',
        'frost': 'Ice crystals on a cold morning',
        'ice': 'Frozen water',
        'rain': 'Water from clouds',
        'sunny': 'Bright with sunshine',
        'warm': 'Pleasantly hot',
        'cool': 'A little cold',
        'leaves': 'They fall from trees in autumn',
        'harvest': 'Gathering the crops',
        'pumpkin': 'A big orange autumn squash',
        'mitten': 'A cozy glove',
        'scarf': 'Wrap it round your neck in winter',
        'sled': 'Ride it down a snowy hill',
        'bloom': 'Flowers do it in spring',
        'june': 'The month of summer weddings',
        'picnic': 'A summer meal outdoors',
        'beach': 'A summer holiday spot',
        'cocoa': 'A warm winter drink',
        'fire': 'Warm up by it in winter',
        'season': 'Spring or fall, for example',
        'year': 'Twelve months',
        'week': 'Seven days',
        'day': 'Twenty-four hours',
        'month': 'About four weeks',
    },
    'Make and play': {
        'art': 'Painting or drawing, for example',
        'paint': 'Colors for a brush',
        'draw': 'Make a picture with a pencil',
        'sketch': 'A quick drawing',
        'craft': 'Something made by hand',
        'knit': 'Make a scarf with needles and yarn',
        'yarn': 'Wool for knitting',
        'sew': 'Join cloth with a needle and thread',
        'thread': 'Fine string for sewing',
        'song': 'Music with words',
        'sing': 'Make music with your voice',
        'dance': 'Move to music',
        'piano': 'An instrument with black and white keys',
        'drum': 'Tap it to keep the beat',
        'flute': 'A wind instrument you blow across',
        'poem': 'Words written in verse',
        'story': 'A tale with a beginning and an end',
        'game': 'Something you play',
        'puzzle': 'Pieces that fit together',
        'kite': 'It flies on a string',
        'ball': 'Round toy to throw',
        'swing': 'Playground seat that goes back and forth',
        'play': 'Have fun',
        'toy': 'Something to play with',
        'bubble': 'A floating ball of soap',
        'crayon': 'A waxy coloring stick',
        'clay': 'Shape it with your hands',
        'photo': 'A picture from a camera',
        'movie': 'A film',
        'hobby': 'Something you enjoy doing in your free time',
        'chess': 'A board game with kings and queens',
        'cards': 'A deck for playing games',
        'quilt': 'Patchwork you can sleep under',
        'checkers': 'Board game where pieces hop and get crowned',
    },
}

# more hand-written themes live in clues_more.py
from clues_more import MORE_THEMES  # noqa: E402
for _name, _words in MORE_THEMES.items():
    THEMES.setdefault(_name, _words)


def all_clues():
    out = {}
    for theme, d in THEMES.items():
        for w, c in d.items():
            out.setdefault(w, c)
    return out
