"""More hand-written themes for the Gentle crosswords (merged into clues.THEMES). Add freely: word -> clue.
Plain, warm American English; a plural answer gets a plural clue, a past-tense answer a past-tense one."""

MORE_THEMES = {
    'Pups at play': {
        'puppy': 'A very young dog',
        'pup': 'Tidbit, when she was tiny',
        'tail': 'It wags when the pups are happy',
        'paw': 'A pup offers one for a high five',
        'paws': 'Muddy prints come from these',
        'bark': 'A dog\'s "hello!"',
        'fetch': 'Throw it, bring it back, repeat',
        'ball': 'Sugarfoot\'s favorite thing to chase',
        'bone': 'A chewy treat buried in the yard',
        'leash': 'It clips on for a walk',
        'collar': 'It holds a name tag',
        'walk': 'A stroll around the block',
        'sniff': 'How a pup reads the news on a walk',
        'nose': 'A pup\'s wet, busy sniffer',
        'fur': 'Soft coat on a pup',
        'treat': 'A little reward for "sit"',
        'sit': 'The first trick most pups learn',
        'stay': '"Wait right there," in dog school',
        'roll': 'Trick that ends belly-up',
        'belly': 'Rub it and a happy pup wiggles',
        'nap': 'Sugarfoot takes one in a sunbeam',
        'bed': 'A pup\'s cozy cushion',
        'toy': 'Squeaky thing to toss',
        'tug': 'Rope game for two pups',
        'wag': 'What a happy tail does',
        'lick': 'A doggy kiss',
        'hug': 'A two-armed hello',
        'yard': 'Grassy place for zoomies',
        'park': 'Green place for a romp',
        'mask': 'Tidbit has a dark one on her face',
        'feet': 'Sugarfoot\'s are white',
        'pals': 'Tidbit and Sugarfoot, to each other',
    },
    'Rainy day': {
        'rain': 'Drops from gray clouds',
        'puddle': 'Something to splash in with boots on',
        'boots': 'Rubber footwear for wet days',
        'umbrella': 'It opens up over your head',
        'drizzle': 'Very light rain',
        'cloud': 'Gray puff that brings showers',
        'window': 'Watch the drops race down it',
        'drops': 'Rain comes down in these',
        'splash': 'What a jump into a puddle makes',
        'thunder': 'Rumble after a flash',
        'rainbow': 'Colorful arc when the sun comes back',
        'cocoa': 'Warm chocolate drink for a gray day',
        'blanket': 'Cozy cover for the couch',
        'book': 'Curl up with one while it pours',
        'puzzle': 'Jigsaw on the table',
        'soup': 'Warm bowl for lunch',
        'tea': 'Hot drink with a bag',
        'nap': 'Rain on the roof makes a fine one',
        'wet': 'Like a dog after a rainy walk',
        'shower': 'A short burst of rain',
        'drip': 'Sound from the gutter',
        'mist': 'Fine, soft rain',
        'coat': 'Put on your rain ___',
        'hood': 'Pull it up when it sprinkles',
        'worm': 'Wiggly visitor after a storm',
        'snail': 'Slow garden visitor on a wet day',
        'damp': 'A little wet',
        'cozy': 'Snug and warm indoors',
    },
    'At the farm': {
        'barn': 'Red building for the animals',
        'cow': 'She gives milk and says "moo"',
        'calf': 'A baby cow',
        'pig': 'Pink farm animal that loves mud',
        'hen': 'She lays the eggs',
        'chick': 'Fluffy yellow baby bird',
        'egg': 'Breakfast from the coop',
        'goat': 'Farm animal that nibbles everything',
        'sheep': 'Wooly farm animal',
        'lamb': 'A baby sheep',
        'horse': 'Farm animal you can ride',
        'pony': 'A small horse',
        'duck': 'Farm bird that quacks',
        'hay': 'Dried grass in bales',
        'tractor': 'Big farm machine with huge wheels',
        'field': 'Where the corn grows',
        'fence': 'It keeps the cows in',
        'gate': 'Swing it open to the pasture',
        'corn': 'Tall crop with ears',
        'wheat': 'Golden grain for bread',
        'silo': 'Tall tower for storing grain',
        'coop': 'Home for the hens',
        'milk': 'White drink from the dairy',
        'apple': 'Orchard fruit',
        'pumpkin': 'Big orange patch find in fall',
        'rooster': 'He crows at dawn',
        'mud': 'Where piglets love to roll',
        'farmer': 'Person who grows food',
        'seeds': 'Plant these in spring',
    },
    'Camping trip': {
        'tent': 'Shelter you set up with poles',
        'camp': 'Pitch a tent for the night',
        'fire': 'Gather round it and tell stories',
        'lantern': 'Light hung in the tent',
        'hike': 'A long walk on a trail',
        'trail': 'Path through the woods',
        'map': 'Guide for finding your way',
        'compass': 'It always points north',
        'canoe': 'Paddle it across the lake',
        'paddle': 'You row a canoe with it',
        'lake': 'Where you swim at camp',
        'stars': 'They sparkle over the campsite',
        'owl': 'Night bird hooting in the trees',
        'pine': 'Tree with needles and cones',
        'log': 'Seat around the campfire',
        'sleep': 'Rest under the stars',
        'pack': 'Backpack full of gear',
        'boots': 'Sturdy shoes for the trail',
        'woods': 'Forest around the camp',
        'cabin': 'Little wooden house in the woods',
        'grill': 'Cook burgers on it',
        'flashlight': 'Beam for the path at night',
        'marsh': 'Wet, reedy spot where frogs sing',
        'stream': 'Little moving water to cross',
        'rock': 'Skip it across the water',
        'moon': 'Night light over the tents',
    },
    'Music room': {
        'piano': 'Instrument with black and white keys',
        'drum': 'Tap it to keep the beat',
        'flute': 'Silver instrument you blow across',
        'violin': 'Four strings and a bow',
        'cello': 'Big string instrument played sitting down',
        'guitar': 'Strum its six strings',
        'harp': 'Tall instrument with many strings',
        'song': 'Music with words',
        'tune': 'A melody you can hum',
        'note': 'A single musical sound',
        'notes': 'Dots on a music page',
        'hum': 'Sing with your mouth closed',
        'sing': 'Use your voice to make music',
        'choir': 'Group of singers',
        'band': 'Group that plays together',
        'beat': 'The steady pulse of a song',
        'rhythm': 'Pattern of beats',
        'melody': 'The part of a song you remember',
        'chord': 'Notes played together',
        'keys': 'Piano parts you press',
        'bow': 'Stick drawn across violin strings',
        'lullaby': 'Soft song at bedtime',
        'duet': 'Song for two',
        'solo': 'Song for one',
        'banjo': 'Twangy string instrument',
        'horn': 'Brass instrument you blow',
        'bell': 'It rings',
        'dance': 'Move to the music',
    },
    'Breakfast table': {
        'toast': 'Bread browned in the morning',
        'butter': 'Spread it on warm toast',
        'jam': 'Fruit spread in a jar',
        'honey': 'Sweet stuff from bees',
        'egg': 'Scrambled or sunny side up',
        'eggs': 'Scrambled breakfast staples',
        'bacon': 'Crispy strips in the pan',
        'waffle': 'Breakfast with little squares',
        'pancake': 'Flat, fluffy stack with syrup',
        'syrup': 'Maple topping for a stack',
        'cereal': 'Bowlful with milk',
        'milk': 'Pour it on your cereal',
        'juice': 'Orange glassful',
        'coffee': 'Morning mug for grownups',
        'tea': 'Hot drink with a bag',
        'mug': 'Big cup with a handle',
        'bowl': 'Cereal holder',
        'spoon': 'Cereal scooper',
        'oats': 'Grain for warm oatmeal',
        'berry': 'Blue or straw, on top of yogurt',
        'banana': 'Yellow fruit you peel',
        'muffin': 'Blueberry bakery treat',
        'bagel': 'Round bread with a hole',
        'yogurt': 'Creamy cup with fruit',
        'napkin': 'Wipe your hands on it',
        'morning': 'Time for breakfast',
        'sunny': 'Kind of egg that\'s "side up"',
    },
    'At the library': {
        'book': 'Something you read, page by page',
        'books': 'Shelves are full of them',
        'page': 'Turn it to read on',
        'shelf': 'Where the books stand in rows',
        'story': 'A tale with a beginning and an end',
        'novel': 'A long story in a book',
        'poem': 'Words written in verse',
        'author': 'Person who writes a book',
        'reader': 'Bookworm',
        'quiet': 'The library\'s favorite sound',
        'card': 'Library ___, for checking out',
        'read': 'Look at words and understand them',
        'chapter': 'Part of a book',
        'cover': 'Front of a book',
        'title': 'Name of a book',
        'atlas': 'Book of maps',
        'map': 'Guide to a place',
        'index': 'List at the back of a book',
        'fable': 'Short story with a lesson',
        'tale': 'A story',
        'hero': 'Main good guy in a story',
        'desk': 'Table for study',
        'lamp': 'Reading light',
        'chair': 'Seat for reading',
        'learn': 'Find out something new',
        'words': 'Books are made of them',
    },
    'Pond life': {
        'pond': 'Small, still water in a garden',
        'frog': 'Green hopper on a lily pad',
        'toad': 'Frog\'s bumpy cousin',
        'duck': 'Pond bird that quacks',
        'swan': 'Graceful white pond bird',
        'fish': 'Swimmer with fins',
        'koi': 'Colorful pond fish',
        'lily': 'Flower that floats',
        'pad': 'A lily ___, for frogs to sit on',
        'reed': 'Tall plant at the water\'s edge',
        'reeds': 'Tall plants along the bank',
        'ripple': 'Tiny wave from a pebble',
        'pebble': 'Small smooth stone',
        'heron': 'Tall wading bird',
        'newt': 'Little pond lizard look-alike',
        'turtle': 'Slow swimmer with a shell',
        'snail': 'Slow creature with a shell',
        'moss': 'Soft green growth on stones',
        'mud': 'Squishy pond bottom',
        'splash': 'Sound of a jump into water',
        'bank': 'Edge of the pond',
        'bridge': 'Walk over the water on it',
        'dragonfly': 'Shimmery flier over the water',
        'tadpole': 'Baby frog with a tail',
        'bubble': 'Little air ball rising up',
        'still': 'Calm and unmoving, like the water',
    },
    'Birdwatching': {
        'bird': 'Feathered flier',
        'birds': 'Feathered visitors to a feeder',
        'robin': 'Red-breasted spring bird',
        'wren': 'Tiny brown songbird',
        'finch': 'Small seed-eating songbird',
        'owl': 'Night bird that hoots',
        'hawk': 'Bird that circles high',
        'eagle': 'Big bird of the mountains',
        'dove': 'Soft-cooing gray bird',
        'crow': 'Clever black bird',
        'jay': 'Bold blue bird',
        'lark': 'Bird that sings at dawn',
        'swallow': 'Swooping bird with a forked tail',
        'heron': 'Tall wading bird',
        'nest': 'A bird\'s home of twigs',
        'egg': 'Something a bird sits on',
        'wing': 'What a bird flaps',
        'wings': 'A bird flaps these',
        'beak': 'Bird\'s bill',
        'feather': 'Soft plume',
        'song': 'Tune from a branch',
        'tweet': 'Little bird sound',
        'feeder': 'It holds seeds in the yard',
        'seed': 'Snack at a feeder',
        'branch': 'Perch on a tree',
        'flock': 'Group of birds',
        'chirp': 'Short, bright bird sound',
    },
    'Picnic day': {
        'picnic': 'Meal on a blanket outdoors',
        'basket': 'Wicker carrier for lunch',
        'blanket': 'Spread it on the grass',
        'sandwich': 'Two slices with a filling',
        'apple': 'Crunchy red fruit',
        'grapes': 'Little green or purple fruits on a stem',
        'lemonade': 'Sweet, sour summer drink',
        'cookie': 'Sweet round treat',
        'cookies': 'Sweet round treats',
        'cheese': 'Cheddar, for example',
        'napkin': 'Wipe your hands on it',
        'park': 'Green place for a picnic',
        'shade': 'Cool spot under a tree',
        'tree': 'Sit beneath it for shade',
        'ants': 'Tiny picnic visitors',
        'sun': 'It warms the afternoon',
        'grass': 'Green blades under the blanket',
        'kite': 'Fly it on a string',
        'ball': 'Toss it after lunch',
        'melon': 'Juicy summer fruit',
        'berries': 'Little summer fruits',
        'cup': 'Something to drink from',
        'lunch': 'Midday meal',
        'breeze': 'Soft, cool wind',
        'friends': 'Good company for a picnic',
    },
    'Baking day': {
        'bake': 'Cook in the oven',
        'oven': 'Warm box for baking',
        'flour': 'White powder in a bread recipe',
        'sugar': 'Sweet white crystals',
        'butter': 'Creamy yellow spread',
        'eggs': 'Crack these into the bowl',
        'whisk': 'Wire tool for beating eggs',
        'bowl': 'Mix the batter in it',
        'batter': 'Runny mix for a cake',
        'dough': 'Mix for bread before baking',
        'knead': 'Push and fold bread dough',
        'rise': 'What bread dough does as it rests',
        'bread': 'A warm loaf',
        'loaf': 'Bread in one piece',
        'cake': 'Frosted birthday treat',
        'cookie': 'Chocolate chip treat',
        'pie': 'Apple dessert with a crust',
        'crust': 'Crisp outside of a pie',
        'icing': 'Sweet frosting',
        'recipe': 'Instructions for a dish',
        'apron': 'Keep flour off your clothes with it',
        'timer': 'It dings when the cookies are done',
        'mitt': 'Oven ___, for hot pans',
        'tray': 'Flat pan for cookies',
        'muffin': 'Little cake in a paper cup',
        'cinnamon': 'Warm spice in a roll',
        'vanilla': 'Sweet flavor from a bean',
        'yeast': 'It makes bread rise',
    },
    'Summer fun': {
        'summer': 'Warmest season of the year',
        'sun': 'It shines bright in July',
        'beach': 'Sandy shore',
        'swim': 'Paddle in the pool',
        'pool': 'Place to cool off',
        'sand': 'Build a castle with it',
        'shell': 'Seaside treasure',
        'wave': 'Ocean ripple to jump',
        'kite': 'Flies on a windy day',
        'ice': 'Frozen water',
        'popsicle': 'Frozen treat on a stick',
        'lemonade': 'Cold drink from a stand',
        'hammock': 'Swinging bed between trees',
        'fireflies': 'Twinkly bugs on summer nights',
        'sprinkler': 'Run through it on the lawn',
        'camp': 'Summer place with cabins',
        'picnic': 'Lunch on a blanket',
        'bike': 'Two-wheeled ride',
        'sunhat': 'Shade you wear',
        'shorts': 'Pants cut off above the knee',
        'melon': 'Juicy summer fruit',
        'garden': 'Where tomatoes grow',
        'porch': 'Sit out here on a warm night',
        'swing': 'Seat that goes back and forth',
        'vacation': 'A trip away from work or school',
    },
    'Cozy winter': {
        'winter': 'The coldest season',
        'snow': 'Soft white flakes',
        'snowman': 'Frosty friend with a carrot nose',
        'sled': 'Ride it down a snowy hill',
        'mittens': 'Warm hand covers',
        'scarf': 'Wrap it around your neck',
        'hat': 'Wooly cover for your head',
        'boots': 'Warm, waterproof shoes',
        'fire': 'Crackling warmth in the fireplace',
        'cocoa': 'Hot chocolate drink',
        'blanket': 'Cozy cover on the couch',
        'quilt': 'Patchwork cover for a bed',
        'sweater': 'Warm knitted top',
        'socks': 'Warm your toes with these',
        'frost': 'Icy lace on the window',
        'ice': 'Frozen water on the pond',
        'skate': 'Glide across a frozen pond',
        'flake': 'One tiny bit of snow',
        'cozy': 'Snug and warm',
        'soup': 'Warm bowl on a cold night',
        'candle': 'Small flickering light',
        'pine': 'Evergreen tree',
        'cabin': 'Snug wooden house',
        'chilly': 'A bit cold',
        'igloo': 'House made of snow blocks',
        'penguin': 'Tuxedoed bird of the ice',
    },
    'Fruit bowl': {
        'apple': 'Crunchy fruit for the teacher',
        'pear': 'Fruit shaped like a light bulb',
        'plum': 'Small purple fruit',
        'peach': 'Fuzzy summer fruit',
        'grape': 'Small round fruit in bunches',
        'lemon': 'Sour yellow citrus',
        'lime': 'Small green citrus',
        'orange': 'Citrus and a color',
        'banana': 'Yellow fruit you peel',
        'cherry': 'Little red fruit on a stem',
        'berry': 'Small juicy fruit',
        'melon': 'Big juicy fruit with a rind',
        'kiwi': 'Fuzzy brown fruit, green inside',
        'mango': 'Sweet tropical fruit',
        'papaya': 'Orange tropical fruit with black seeds',
        'fig': 'Soft, sweet fruit',
        'date': 'Sweet fruit of a palm',
        'coconut': 'Hairy fruit with milk inside',
        'apricot': 'Small orange fruit, often dried',
        'guava': 'Tropical fruit with pink flesh',
        'peel': 'Skin of a banana',
        'seed': 'A pip in an apple',
        'pit': 'Hard middle of a peach',
        'juicy': 'Full of juice',
        'ripe': 'Ready to eat',
        'bowl': 'Dish that holds the fruit',
    },
    'Vegetable patch': {
        'carrot': 'Orange root a bunny loves',
        'pea': 'Little green ball in a pod',
        'peas': 'Little green balls in a pod',
        'bean': 'Green veggie on a vine',
        'corn': 'Yellow ears on tall stalks',
        'kale': 'Curly leafy green',
        'lettuce': 'Salad leaves',
        'tomato': 'Red fruit we call a vegetable',
        'potato': 'Mash it, bake it, fry it',
        'onion': 'Layered bulb that makes eyes water',
        'garlic': 'Bulb with cloves',
        'pepper': 'Bell-shaped veggie',
        'squash': 'Big fall vegetable',
        'pumpkin': 'Orange squash for fall',
        'radish': 'Small red root with a bite',
        'beet': 'Deep red root',
        'celery': 'Crunchy green stalk',
        'spinach': 'Leafy green for a salad',
        'cabbage': 'Round leafy head',
        'sprout': 'A tiny new shoot',
        'seeds': 'Plant these in rows',
        'soil': 'Dirt for growing',
        'rake': 'Garden tool with teeth',
        'water': 'What every plant needs',
        'rows': 'Neat lines of plants',
        'harvest': 'Pick the crops',
    },
    'Sweet dreams': {
        'sleep': 'Rest with your eyes closed',
        'dream': 'Story your mind tells at night',
        'dreams': 'Stories your mind tells at night',
        'pillow': 'Soft place for your head',
        'bed': 'Where you sleep',
        'blanket': 'Warm cover at night',
        'pajamas': 'Clothes for bedtime',
        'yawn': 'Big sleepy breath',
        'nap': 'Short sleep',
        'rest': 'Relax and recharge',
        'moon': 'Night light in the sky',
        'star': 'Twinkle, twinkle, little one',
        'night': 'Time for sleeping',
        'hush': 'Soft "shh"',
        'lullaby': 'Soft song for bedtime',
        'snore': 'Sleepy rumble',
        'teddy': 'Stuffed bear to cuddle',
        'cuddle': 'Snuggle close',
        'snuggle': 'Cuddle up warmly',
        'quiet': 'Hushed and still',
        'calm': 'Peaceful',
        'story': 'Bedtime tale',
        'lamp': 'Turn it off before sleep',
        'dozy': 'Sleepy',
        'sleepy': 'Ready for bed',
        'owl': 'Bird awake while you sleep',
    },
    'Colors all around': {
        'red': 'Color of a ripe strawberry',
        'blue': 'Color of a clear sky',
        'green': 'Color of grass',
        'yellow': 'Color of a lemon',
        'orange': 'Color of a pumpkin',
        'purple': 'Color of grapes',
        'pink': 'Color of cotton candy',
        'brown': 'Color of cocoa',
        'gray': 'Color of a rain cloud',
        'white': 'Color of fresh snow',
        'black': 'Color of the night sky',
        'gold': 'Color of sunshine on a sunflower',
        'silver': 'Color of the moon',
        'teal': 'Blue-green color',
        'navy': 'Very dark blue',
        'coral': 'Pinkish orange',
        'lilac': 'Pale purple',
        'peach': 'Soft orange-pink',
        'mint': 'Pale green',
        'cream': 'Off-white',
        'ruby': 'Deep red',
        'amber': 'Golden brown',
        'rainbow': 'Every color in an arc',
        'paint': 'Colors for a brush',
        'crayon': 'A waxy coloring stick',
        'color': 'Hue',
    },
}
